"""really delete comment column

Revision ID: cfc62f27acb4
Revises: 
Create Date: 2026-04-17 15:30:46.590611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc62f27acb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cobalt_prices', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cobalt_prices', sa.Column('comment', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
